// <auto-generated />
namespace Neshagostar.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class mig84731 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mig84731));
        
        string IMigrationMetadata.Id
        {
            get { return "201911101916513_mig84731"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
