// <auto-generated />
namespace Neshagostar.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class mig9685 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mig9685));
        
        string IMigrationMetadata.Id
        {
            get { return "201911031533466_mig9685"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
